[package]
name = "move_to_guandan"
version = "0.0.1"
authors = []

[addresses]
move_to_guandan = "_"

[dev-addresses]

[dependencies]
AptosFramework = { local = "../aptos-core/aptos-move/framework/aptos-framework" }

[dev-dependencies]
